// © 2026 Bigfin
export const ERRORS = {
  DEAL_NOT_FOUND: 'DEAL_NOT_FOUND',
  CONTACT_NOT_FOUND: 'CONTACT_NOT_FOUND',
  DEAL_HAS_OPERATIONS: 'DEAL_HAS_OPERATIONS',
  STAGE_NOT_FOUND: 'STAGE_NOT_FOUND',
  STAGE_NAME_REQUIRED: 'STAGE_NAME_REQUIRED',
  STAGE_NEGATIVE_AMOUNT: 'STAGE_NEGATIVE_AMOUNT',
  STAGE_CLOSE_NEEDS_DATE: 'STAGE_CLOSE_NEEDS_DATE',
};

export const DEAL_STATUSES = ['in_progress', 'completed', 'cancelled'] as const;
export const DEFAULT_DEAL_STATUS = 'in_progress';
