export const ERRORS = {
  TWO_FACTOR_ALREADY_ENABLED: 'TWO_FACTOR_ALREADY_ENABLED',
  TWO_FACTOR_NOT_ENABLED: 'TWO_FACTOR_NOT_ENABLED',
  TWO_FACTOR_NOT_CONFIGURED: 'TWO_FACTOR_NOT_CONFIGURED',
  TWO_FACTOR_INVALID_CODE: 'TWO_FACTOR_INVALID_CODE',
  TWO_FACTOR_INVALID_PASSWORD: 'TWO_FACTOR_INVALID_PASSWORD',
  TWO_FACTOR_TOKEN_INVALID: 'TWO_FACTOR_TOKEN_INVALID',
};
